### ISSUE TITLE
Unable to decompile this CompiledCode.bin

### ISSUE THREAD

**Issue by 9844201** [Wack0/IFPSTools.NET#3]
Unable to decompile this CompiledCode.bin
[CompiledCode.zip](https://github.com/Wack0/IFPSTools.NET/files/13319886/CompiledCode.zip)

**Comment by Wack0** [comment]
This file looks corrupt, it appears any byte with bit 7 set has been replaced by `'?'`.

**Comment by attikov** [comment]
> This file looks corrupt, it appears any byte with bit 7 set has been replaced by `'?'`

ftp transferred in text mode?
